- hosts: RaspberryPi

  tasks:
    - name: Upgrade cloudflared package
      command: cloudflared update
      register: upgrade_result
      changed_when: "'Updated to version' in upgrade_result.stdout or 'Cloudflared is up to date' not in upgrade_result.stdout"

    - name: Restart cloudflared service if package was upgraded
      systemd:
        name: cloudflared
        state: restarted
        daemon_reload: yes
      when: upgrade_result.changed