- hosts: all

  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required